DROP DATABASE IF EXISTS MaintHelp;
CREATE DATABASE MaintHelp;
USE MaintHelp;
CREATE TABLE AZIENDA (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255)
);
CREATE TABLE UTENTE (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    NOME VARCHAR(255),
    COGNOME VARCHAR(255),
    RUOLO VARCHAR(255),
    AZIENDA_ID INT,
    FOREIGN KEY (AZIENDA_ID) REFERENCES AZIENDA(ID)
);

CREATE TABLE MACCHINARIO (
     ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255),
    STATO BOOLEAN,
    SCHEMA_ELECT VARCHAR(255),
    SCHEMA_MEC VARCHAR(255),
    PROSSIMA_MANUTENZIONE DATE,
    ULTIMA_MANUTENZIONE DATE,
    CHIAMATA_MANUTENTORE BOOLEAN,
    AZIENDA_ID INT,
    FOREIGN KEY (AZIENDA_ID) REFERENCES AZIENDA(ID)
);

CREATE TABLE GUASTO (
     ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    TIPOGUASTO VARCHAR(255)
);

CREATE TABLE DOCUMENTO (
     ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255),
    TIPODOCUMENTO VARCHAR(255),
    TIPOGUASTO VARCHAR(255),
    DATA_INVIA DATE,
    MANUTENTORE_ID INT,
    OPERATORE_ID INT,
    TIPO_MANUTENZIONE VARCHAR(255),
    ORE_MANUTENZIONE INT,
    DESCRIZIONE TEXT,
    DATA_SCRIVE DATE,
    MACCHINARIO_ID INT,
    GUASTO_ID INT,
    FOREIGN KEY (MANUTENTORE_ID) REFERENCES UTENTE(ID),
    FOREIGN KEY (OPERATORE_ID) REFERENCES UTENTE(ID),
    FOREIGN KEY (MACCHINARIO_ID) REFERENCES MACCHINARIO(ID),
    FOREIGN KEY (GUASTO_ID) REFERENCES GUASTO(ID)
);
ALTER TABLE `DOCUMENTO` DROP FOREIGN KEY `DOCUMENTO_ibfk_1`; ALTER TABLE `DOCUMENTO` ADD CONSTRAINT `DOCUMENTO_ibfk_1` FOREIGN KEY (`MANUTENTORE_ID`) REFERENCES `UTENTE`(`ID`) ON DELETE SET NULL ON UPDATE SET NULL; ALTER TABLE `DOCUMENTO` DROP FOREIGN KEY `DOCUMENTO_ibfk_2`; ALTER TABLE `DOCUMENTO` ADD CONSTRAINT `DOCUMENTO_ibfk_2` FOREIGN KEY (`OPERATORE_ID`) REFERENCES `UTENTE`(`ID`) ON DELETE SET NULL ON UPDATE SET NULL;
INSERT INTO AZIENDA (NOME) VALUES ('EcoFusion Innovations');
INSERT INTO AZIENDA (NOME) VALUES ('LuminovaTech Solutions');
INSERT INTO UTENTE (USERNAME, PASSWORD, NOME, COGNOME, RUOLO,AZIENDA_ID) VALUES ('pippo', '153547d40c4320a3f7bb11f3435d2d49', 'PIPPO', 'QUADRATO', 'OPERATORE',1);
INSERT INTO UTENTE (USERNAME, PASSWORD, NOME, COGNOME, RUOLO,AZIENDA_ID) VALUES ('admin', '153547d40c4320a3f7bb11f3435d2d49', 'silvia', 'arnoldi', 'AMMINISTRATORE',1);
INSERT INTO UTENTE (USERNAME, PASSWORD, NOME, COGNOME, RUOLO,AZIENDA_ID) VALUES ('mari', '153547d40c4320a3f7bb11f3435d2d49', 'mario', 'rossi', 'MANUTENTORE', 1);
INSERT INTO UTENTE (USERNAME, PASSWORD, NOME, COGNOME, RUOLO,AZIENDA_ID) VALUES ('gianni', '153547d40c4320a3f7bb11f3435d2d49', 'giovanni', 'cubo', 'OPERATORE',2);
INSERT INTO UTENTE (USERNAME, PASSWORD, NOME, COGNOME, RUOLO,AZIENDA_ID) VALUES ('lollo', '153547d40c4320a3f7bb11f3435d2d49', 'lorenzo', 'ciccioli', 'AMMINISTRATORE',2);
INSERT INTO UTENTE (USERNAME, PASSWORD, NOME, COGNOME, RUOLO,AZIENDA_ID) VALUES ('mimi', '153547d40c4320a3f7bb11f3435d2d49', 'miriam', 'cina', 'MANUTENTORE', 2);
INSERT INTO MACCHINARIO (NOME, STATO, SCHEMA_ELECT,SCHEMA_MEC,PROSSIMA_MANUTENZIONE,ULTIMA_MANUTENZIONE,CHIAMATA_MANUTENTORE,AZIENDA_ID) VALUES ('Macchinario1', 1, 'img/schemaE1.png', 'img/schemaM1.png', '2024-01-01', '2023-12-01', 0,1);
INSERT INTO MACCHINARIO (NOME, STATO, SCHEMA_ELECT,SCHEMA_MEC,PROSSIMA_MANUTENZIONE,ULTIMA_MANUTENZIONE,CHIAMATA_MANUTENTORE,AZIENDA_ID) VALUES ('Macchinario2', 1, 'img/schemaE2.png', 'img/schemaM2.png', '2024-01-01', '2023-12-01', 0,1);
INSERT INTO MACCHINARIO (NOME, STATO, SCHEMA_ELECT,SCHEMA_MEC,PROSSIMA_MANUTENZIONE,ULTIMA_MANUTENZIONE,CHIAMATA_MANUTENTORE,AZIENDA_ID) VALUES ('Macchinario3', 1, 'img/schemaE3.png', 'img/schemaM3.png', '2024-01-01', '2023-12-01', 0,1);
INSERT INTO MACCHINARIO (NOME, STATO, SCHEMA_ELECT,SCHEMA_MEC,PROSSIMA_MANUTENZIONE,ULTIMA_MANUTENZIONE,CHIAMATA_MANUTENTORE,AZIENDA_ID) VALUES ('Macchinario4', 1, 'img/schemaE4.png', 'img/schemaM4.png', '2024-01-01', '2023-12-01', 0,2);
INSERT INTO MACCHINARIO (NOME, STATO, SCHEMA_ELECT,SCHEMA_MEC,PROSSIMA_MANUTENZIONE,ULTIMA_MANUTENZIONE,CHIAMATA_MANUTENTORE,AZIENDA_ID) VALUES ('Macchinario5', 1, 'img/schemaE5.png', 'img/schemaM5.png', '2024-01-01', '2023-12-01', 0,2);
INSERT INTO GUASTO (TIPOGUASTO) VALUES ('Elettrico');
INSERT INTO GUASTO (TIPOGUASTO) VALUES ('Meccanico');
INSERT INTO GUASTO (TIPOGUASTO) VALUES ('ElettricoInformatico');
INSERT INTO GUASTO (TIPOGUASTO) VALUES ('Altro');

